// Import the Navigation component which will be the top navigation bar
import Navigation from "@/components/Navigation";

// Import different font weights of Roboto for Material-UI and general use
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

// Import Google fonts Geist and Geist Mono using Next.js font optimization
import { Geist, Geist_Mono } from "next/font/google";

// Import a custom authentication context provider
import { AuthProvider } from "./context/AuthContext";

// Import global CSS styles
import "./globals.css";

// Import a store provider (likely for state management, e.g., Zustand or Redux)
import StoreProvider from "./StoreProvider";

// Load Geist Sans font and assign it to a CSS variable for usage
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"], // Only load Latin characters
});

// Load Geist Mono font and assign it to a CSS variable
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for the site, used in <head> for SEO and page info
export const metadata = {
  title: "Create Next App",         // Page title
  description: "Generated by create next app", // Page description
};

// Define the RootLayout component which wraps the entire app
export default function RootLayout({ children }) {
  return (
    // HTML root element with English language
    <html lang="en">
      {/* Body element with fonts applied and smooth font rendering */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the app with AuthProvider to provide authentication context */}
        <AuthProvider>
          {/* Wrap the app with StoreProvider to provide global state */}
          <StoreProvider>
            {/* Navigation component wraps children so the nav is always visible */}
            <Navigation>{children}</Navigation>
          </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
